services:
  api:
    build: api
    ports: 
      - "8000:8000"
    networks:
      - frontend
      - backend
    depends_on:
      - mongodb
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=mongodb
    volumes:
      - ./api/uploads:/uploads  # Bind mount for image uploads

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - backend
    volumes:
      - mongo-data:/data/db
      - ./mongod.conf:/etc/mongod.conf  # Mount the custom configuration file
    command: mongod --config /etc/mongod.conf  # Use the custom configuration file

  web:
    build: web
    ports:
      - "5000:5000"
    networks:
      - frontend
    depends_on:
      - api

  xmr_wallet:
    build: xmr_wallet
    ports:
      - "18081:18081"
      - "18082:18082"
    networks:
      - backend
networks:
  frontend:
  backend:

volumes:
  mongo-data: